/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { HousingOfferingService } from "../housingOffering.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { HousingOfferingCreateInput } from "./HousingOfferingCreateInput";
import { HousingOfferingWhereInput } from "./HousingOfferingWhereInput";
import { HousingOfferingWhereUniqueInput } from "./HousingOfferingWhereUniqueInput";
import { HousingOfferingFindManyArgs } from "./HousingOfferingFindManyArgs";
import { HousingOfferingUpdateInput } from "./HousingOfferingUpdateInput";
import { HousingOffering } from "./HousingOffering";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class HousingOfferingControllerBase {
  constructor(
    protected readonly service: HousingOfferingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "HousingOffering",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: HousingOffering })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: HousingOfferingCreateInput
  ): Promise<HousingOffering> {
    return await this.service.create({
      data: {
        ...data,

        author: {
          connect: data.author,
        },
      },
      select: {
        address: true,

        author: {
          select: {
            id: true,
          },
        },

        city: true,
        createdAt: true,
        description: true,
        id: true,
        price: true,
        roomsNumber: true,
        size: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "HousingOffering",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [HousingOffering] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(HousingOfferingFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<HousingOffering[]> {
    const args = plainToClass(HousingOfferingFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        address: true,

        author: {
          select: {
            id: true,
          },
        },

        city: true,
        createdAt: true,
        description: true,
        id: true,
        price: true,
        roomsNumber: true,
        size: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "HousingOffering",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: HousingOffering })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: HousingOfferingWhereUniqueInput
  ): Promise<HousingOffering | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        address: true,

        author: {
          select: {
            id: true,
          },
        },

        city: true,
        createdAt: true,
        description: true,
        id: true,
        price: true,
        roomsNumber: true,
        size: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "HousingOffering",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: HousingOffering })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: HousingOfferingWhereUniqueInput,
    @common.Body() data: HousingOfferingUpdateInput
  ): Promise<HousingOffering | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          author: {
            connect: data.author,
          },
        },
        select: {
          address: true,

          author: {
            select: {
              id: true,
            },
          },

          city: true,
          createdAt: true,
          description: true,
          id: true,
          price: true,
          roomsNumber: true,
          size: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "HousingOffering",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: HousingOffering })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: HousingOfferingWhereUniqueInput
  ): Promise<HousingOffering | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          address: true,

          author: {
            select: {
              id: true,
            },
          },

          city: true,
          createdAt: true,
          description: true,
          id: true,
          price: true,
          roomsNumber: true,
          size: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
